#if there are multiple implementations available, pick one of these: (55|54|53|52|51|jit|j) 
# see https://luajava.iroiro.party/jsr223.html#lua-versions or LuaScriptEngineFactory.findAvailableEngine()
#luajava.jsr-223=jit